server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Берём только stdout/stderr
      - source_labels: ['__meta_docker_container_log_stream']
        regex: 'stdout|stderr'
        action: keep

      # Имя контейнера
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'

      # Имя сервиса из docker-compose
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'

      # Имя проекта (compose project)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

      # Путь до файла логов контейнера → обязателен, иначе promtail не знает, что читать
      - source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'
