server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Имя Docker контейнера
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'

      # Имя сервиса из docker-compose (то, что нам нужно!)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'

      # Имя проекта (имя папки compose)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

      # Полный образ
      - source_labels: ['__meta_docker_image_name']
        target_label: 'image'

      # Не добавлять compose_service, если значение пустое
      - regex: ''
        action: drop
        source_labels: ['compose_service']
