global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'marketplace-backend'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - marketplace-backend:3000
